#                        Copyright (C) 2016 EntirelyQuartz                                                                                       
#  ,ad8888ba,    88        88         db         88888888ba   888888888888  888888888888  
# d8"'    `"8b   88        88        d88b        88      "8b       88                ,88  
#d8'        `8b  88        88       d8'`8b       88      ,8P       88              ,88"   
#88          88  88        88      d8'  `8b      88aaaaaa8P'       88            ,88"     
#88          88  88        88     d8YaaaaY8b     88""""88'         88          ,88"       
#Y8,    "88,,8P  88        88    d8""""""""8b    88    `8b         88        ,88"         
# Y8a.    Y88P   Y8a.    .a8P   d8'        `8b   88     `8b        88       88"           
#  `"Y8888Y"Y8a   `"Y8888Y"'   d8'          `8b  88      `8b       88       888888888888  
#  
---
#
# If inverse mode is enabled, all blocks will have an amount of health by default
#
inverseMode: false
inverseDefaultHealth: 4
#
# Usage: "blockId : amountOfHeal"
# If inverse mode isn't enabled, only blocks here will have health.
# If inverse mode is enabled, all blocks will have health, but blocks here will have a...
# different amount of health.
#
'blocks': {49: 10}
#
# If regeneration is enabled, all blocks will regenerate health
#
regeneration: false
#
# If regeneration is enabled, all blocks will regenerate each
# regenerationSeconds seconds.
#
regenerationSeconds: 20
#
# If regeneration is enabled, all blocks will regenerate each
# regerationSeconds seconds regenerationAmount of health.
#
regenerationAmount: 1
#
# Messages
#
removeMessage: ""
removePopup: "{RED}> {GREEN}Block health: {rn}/{max} {RED}<"
#
# NEW! <3 Multi-level support
# If enableAllWorlds is enabled, the plugin will work on all levels
# if not, only on worlds defined inside worlds
#
enableAllWorlds: true
worlds:
- "world"
- "wild"
- "teset"
...